/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c40d95a2-174b-4fe1-8c80-d87a4931a2c0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GSsB9FPWB",
    "aws_user_pools_web_client_id": "3i9hvm3av776j94b0jqs1ahtia",
    "oauth": {}
};


export default awsmobile;
